# Generated by Django 3.1.7 on 2021-03-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'complete'), ('in_progress', 'in progress')], default='in_progress', max_length=15)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('proc_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
